### ISSUE TITLE
server dont start

### ISSUE THREAD

**Issue by dev-101010** [ComputerBaer/ARK-Linux-Server-Script-v2#3]
The old script worked nice, with some missing things, like additional settings (mod and egg/baby times).
But the V2 not work at all for me...

Start:
![arkserver1](https://cloud.githubusercontent.com/assets/8311861/13201392/6cbb41a8-d86f-11e5-9d49-b7aea8494007.png)
Status:
![arkserver2](https://cloud.githubusercontent.com/assets/8311861/13201393/6cc01bce-d86f-11e5-9cbe-793a495504a4.png)

There are no Ark logs. ".ArkServer(pid?)" is created, but apparently not found from script.

"screen /home/steam/game/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?listen?SessionName=Z-ServArkServer?ServerAdminPassword=xxxxxxxxxx -server -log"
Works, so the server is fine.

**Comment by ComputerBaer** [comment]
Ich nehme an die ".ArkServer" befindet sich selben Ordner wie die "arkserver.sh"? Dann kannst du die einfach löschen. (Das ist eine Kopie der "game/ShooterGame/Binaries/Linux/ShooterGameServer", die dort nicht sein soll und vom Skript nicht verwendet wird.)

Ich habe bei meinen letzten Änderungen, die ich dummerweise nicht getestet habe, wohl einen Fehler eingebaut. Jetzt sollte es wieder funktionieren.

**Comment by dev-101010** [comment]
Hey super, teste ich nachher.
Hatte mich jetzt schon etwas eingearbeitet, dachte nicht das du so schnell bist.^^
Wenn du die .Arkserver nutzen möchtest, muss die im gleichen DIR bleiben, sonst findet die ihre librarys nicht. Hatte sicher den sinn mehrerer Instancen, oder?

Noch eine Kleinigkeit: "StopGame" sagt immer gestoppt, auch wenn nicht am laufen.
Kann ein bisschen irritieren.
Kann mit github leider noch nicht so umgehen, da für mich absolut neu. Daher schreib ich dir den code einfach so:

function StopGame
{
    GameStatus
    if [[ $GAME_IS_RUNNING == true ]]; then
        screen -S $InstanceName -X quit > /dev/null

```
    sleep $GAME_STOP_WAIT &
    WaitForBackgroundProcess $! $FG_YELLOW

    local EXEC_NAME=$(basename $GAME_EXECUTABLE_INSTANCE)
    local PROCESS_IDS=$(pgrep -f $EXEC_NAME)

    if [[ ! -z $PROCESS_IDS ]]; then
        kill -9 $(pgrep -f $EXEC_NAME)
    fi
    echo -e "${FG_YELLOW}${STR_GAME_STOPPED}${RESET_ALL}"
else
    echo -e "${FG_RED}${STR_GAME_RUNNING_NOT}${RESET_ALL}"
fi
```

}

**Comment by ComputerBaer** [comment]
Das mit der ".ArkServer" war ein Fehler, die kannst du löschen. Das Skript erstellt die Kopie jetzt wieder an der richtigen Stelle. Und ja, das wird für die bessere Erkennung von mehreren Instanzen verwendet.

Deinen Vorschlag für StopGame habe ich eingefügt.

**Comment by dev-101010** [comment]
Top support! Danke
